In [2]:
import numpy as np

In [3]:
a = [4,5,3]
b = [7,5,2]
print(a+b)

[4, 5, 3, 7, 5, 2]


In [4]:
# list are "not mathematical entities" they are data entities
# array can have mathematical calculation or operation

In [6]:
a = np.array([1,2,4])
b = np.array([4,2,1])
print(a+b)

[5 4 5]


In [7]:
# with numpy array can create a multi-dimensional array
m = np.array([[4,2,6],[2,3,4],[6,1,5]])
m

array([[4, 2, 6],
       [2, 3, 4],
       [6, 1, 5]])

In [8]:
# for calculating the dimension
a.ndim

1

In [9]:
a.shape

(3,)

In [10]:
m.ndim

2

In [11]:
m.shape

(3, 3)

In [12]:
print(m.min())
print(m.max())
print(m.mean())
print(m.std())

1
6
3.6666666666666665
1.699673171197595


### Mathematical calculation with numpy

In [15]:
m

array([[4, 2, 6],
       [2, 3, 4],
       [6, 1, 5]])

In [16]:
print(np.mean(m), np.median(m), np.std(m), np.var(m))

3.6666666666666665 4.0 1.699673171197595 2.888888888888889


In [17]:
print(np.sin(np.deg2rad(90)))

1.0


In [18]:
print(np.log10(1000))
print(np.exp(1.25))

3.0
3.4903429574618414


## Generating array with numpy

In [19]:
x = np.arange(start=3, stop=25,step=1.5)
x

array([ 3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. , 16.5, 18. ,
       19.5, 21. , 22.5, 24. ])

In [22]:
x= np.linspace(start=3 , stop=25, num = 12)
x

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.])

In [24]:
x= np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [26]:
x = np.ones((2,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Genearte random numbers with numpy

In [28]:
# generating an array with uniform distribution b/w 0  and 1
x = np.random.rand(10)
x

array([0.42891299, 0.60182371, 0.18311113, 0.40112423, 0.02739504,
       0.85572084, 0.45385296, 0.97387869, 0.31374679, 0.71500837])

In [33]:
# genrating normal distribution with mean =0 and std = -1
x = np.random.randn(10)
x

array([-0.92849713,  0.6086051 , -0.65053641, -0.35508374,  0.56274928,
        1.42432703,  2.97444996, -0.7171844 ,  0.171231  ,  0.56087752])

In [35]:
# generate integer random numbers
x = np.random.randint(10,100,5)
x

array([87, 19, 24, 97, 21])

In [37]:
# use same random numbers
np.random.seed(3)
# generate integer random numbers
x = np.random.randint(10,100,5)
x

array([34, 13, 66, 82, 10])

In [38]:
np.random.seed(3)
# generate integer random numbers
x = np.random.randint(10,100,5)
x

array([34, 13, 66, 82, 10])

### Linear Algebra with Numpy

In [39]:
m

array([[4, 2, 6],
       [2, 3, 4],
       [6, 1, 5]])

In [40]:
np.linalg.inv(m)

array([[-0.45833333,  0.16666667,  0.41666667],
       [-0.58333333,  0.66666667,  0.16666667],
       [ 0.66666667, -0.33333333, -0.33333333]])

In [42]:
np.linalg.matrix_rank(m)

3

In [43]:
# determinant of the matrix
np.linalg.det(m)

-24.000000000000004

# Solve of X & Y 
3x - 4y = 1
4x +2y = 16

In [45]:
# create a list of coefficients
a = [[3,-4],[4,2]]
# list of constants
b = [1,16]

np.linalg.solve(a,b)

array([3., 2.])